---
- name: Create ansibleuser with sudo access and verify creation
  hosts: all
  become: true

  vars:
    username: ansibleuser
    password: bulletx2

  tasks:
    - name: Create ansibleuser
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Grant sudo access to ansibleuser
      lineinfile:
        dest: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: visudo -cf %s
        state: present
      become: true

    - name: Verify ansibleuser creation
      command: id ansibleuser
      register: user_check
      ignore_errors: true

    - name: Print user existence status
      debug:
        msg: "ansibleuser exists"
      when: user_check.rc == 0

    - name: Print user non-existence status
      debug:
        msg: "ansibleuser does not exist"
      when: user_check.rc != 0
