- hosts: all
  vars:
    id_rsa_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    passphrase: "bulletx2"
    ansible_user: "ansibleuser"
    ansible_password: "bulletx2"
  tasks:
    - stat:
        path: "{{ id_rsa_file }}"
      register: op

    - name: Generating ssh key pair
      command: ssh-keygen -t rsa -b 4096 -f "{{ id_rsa_file }}" -q -N "{{ passphrase }}"
      when: op.stat.exists == false

    - debug:
        msg: "Key pair already exists. Using the same key."
      when: op.stat.exists

    - name: Copy public key to the nodes
      command: sshpass -p "{{ ansible_password }}" ssh-copy-id -i "{{ id_rsa_file }}.pub" {{ ansible_user }}@"{{ ansible_host }}" -o StrictHostKeyChecking=no

