- hosts: all
  vars:
    id_rsa_file: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    passphrase: "bulletx2"
    ansible_user: "ansibleuser"
    ansible_password: "bulletx2"
  tasks:
    - stat:
        path: "{{ id_rsa_file }}"
      register: op

    - name: Generating ssh key pair
      command: ssh-keygen -t rsa -b 4096 -f "{{ id_rsa_file }}" -q -N "{{ passphrase }}"
      when: op.stat.exists == false

    - debug:
        msg: "Key pair already exists. Using the same key."
      when: op.stat.exists

    - name: Copy public key to the nodes
      command: sshpass -p "{{ ansible_password }}" ssh-copy-id -i "{{ id_rsa_file }}.pub" -o StrictHostKeyChecking=no {{ ansible_user }}@"{{ ansible_host }}"
      register: copy_key_result

    - name: Set correct permissions for private key
      file:
        path: "{{ id_rsa_file }}"
        mode: 0600

    - name: Get SSH host key
      command: ssh-keyscan -H {{ inventory_hostname }}
      register: ssh_host_key

    - name: Add remote host to known_hosts
      lineinfile:
        path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
        line: "{{ ssh_host_key.stdout }}"

    - name: Check connection
      command: ssh -o ConnectTimeout=5 -i "{{ id_rsa_file }}" {{ ansible_user }}@"{{ ansible_host }}" exit
      register: result
      ignore_errors: true

    - debug:
        msg: "Connection successful."
      when: result.rc == 0

    - debug:
        msg: "Connection failed."
      when: result.rc != 0
