- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if SSH key exists on control machine
      stat:
        path: "~/.ssh/ansible"
      register: ssh_key

    - name: Generate SSH key on control machine
      command: ssh-keygen -t rsa -b 2048 -f ~/.ssh/ansible -N ""
      when: not ssh_key.stat.exists

    - name: Ensure ssh-agent is running
      shell: eval "$(ssh-agent -s)"
      changed_when: false

    - name: Add SSH key to ssh-agent
      shell: ssh-add ~/.ssh/ansible
      changed_when: false

- hosts: all
  become: yes
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_pass: replaceme
    user_name: ansibleuser

  tasks:
    - name: Create a new user
      user:
        name: "{{ user_name }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Read public key from control machine
      command: cat ~/.ssh/ansible.pub
      delegate_to: localhost
      register: public_key
      changed_when: false

    - name: Set up authorized key for the new user
      authorized_key:
        user: "{{ user_name }}"
        key: "{{ public_key.stdout }}"

    - name: Ensure 'ansibleuser' can execute sudo commands without a password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%{{ user_name }}'
        line: '{{ user_name }} ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
