- hosts: all
  become: yes
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_pass: replaceme
    user_name: ansibleuser

  tasks:
    - name: Create a new user
      user:
        name: "{{ user_name }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Check if SSH key exists on control machine
      stat:
        path: "~/.ssh/ansible"
      register: ssh_key

    - name: Generate SSH key on control machine
      command: ssh-keygen -t rsa -b 2048 -f ~/.ssh/ansible -N ""
      when: not ssh_key.stat.exists

    - name: Read public key
      command: cat ~/.ssh/ansible.pub
      register: public_key
      changed_when: false

    - name: Set up authorized key for the new user
      authorized_key:
        user: "{{ user_name }}"
        key: "{{ public_key.stdout }}"
