---
- name: Configure Cluster Hosts and Install Docker CE
  hosts: ubuntu
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "192.168.68.80 manager-1"
        - "192.168.68.82 manager-2"
        - "192.168.68.82 manager-3"

    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

- name: Initialize Docker Swarm
  hosts: ubuntu
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: Initialize Docker Swarm on Manager Node
      command: docker swarm init --advertise-addr 192.168.68.81
      register: swarm_init

    - name: Set Swarm Manager Token Fact
      set_fact:
        swarm_manager_token: "{{ swarm_init.stdout | regex_search('(SWMTKN[^\\n]+)', '\\1') }}"
      when: swarm_init is changed

- name: Join Docker Swarm as Manager Nodes
  hosts: ubuntu:!dl380
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: Join Swarm as a Manager
      command: docker swarm join --token {{ hostvars['dl380']['swarm_manager_token'] }} 192.168.68.80:2377
