---
- name: Configure Cluster Hosts and Install Docker CE
  hosts: ubuntu
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "192.168.68.80 dl380"
        - "192.168.68.81 x3650"
        - "192.168.68.82 r730"

    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Install Keepalived
      apt:
        name: keepalived
        state: present
- name: Initialize Docker Swarm
  hosts: dl380
  become: yes
  remote_user: ansibleuser
  tasks:
    - name: Initialize Docker Swarm on Manager Node
      command: docker swarm init --advertise-addr 192.168.68.80
      register: swarm_init_output

    - name: Set Swarm Worker Token Fact
      set_fact:
        swarm_worker_token: "{{ swarm_init_output.stdout | regex_search('docker swarm join --token (\\S+)', '\\1') | first }}"

    - name: Store Swarm Worker Token
      copy:
        content: "{{ swarm_worker_token }}"
        dest: "./swarm_worker_token.txt"
      delegate_to: localhost

    - name: Get Swarm Manager Join Token
      command: docker swarm join-token --quiet manager
      register: swarm_manager_token_output

    - name: Set Swarm Manager Token Fact
      set_fact:
        swarm_manager_token: "{{ swarm_manager_token_output.stdout }}"

    - name: Store Swarm Manager Token
      copy:
        content: "{{ swarm_manager_token }}"
        dest: "./swarm_manager_token.txt"
      delegate_to: localhost

- name: Join Docker Swarm as Manager Nodes
  hosts: ubuntu:!dl380
  become: yes
  remote_user: ansibleuser
  tasks:
    - name: Join Swarm as a Manager
      command: docker swarm join --token {{ hostvars['dl380']['swarm_manager_token'] }} 192.168.68.80:2377
    - name: Configure Keepalived on all nodes
      hosts: ubuntu
      become: yes
      remote_user: ansibleuser
      tasks:
        - name: Configure Keepalived
          template:
            src: keepalived.conf.j2
            dest: /etc/keepalived/keepalived.conf
          vars:
            priority_map:
              dl380: 150
              x3650: 100
              r730: 50
            virtual_ip: 192.168.68.79
          notify: restart keepalived
    
      handlers:
        - name: restart keepalived
          systemd:
            name: keepalived
            state: restarted
