- name: Install and configure GlusterFS on all nodes
  hosts: ubuntu
  become: yes
  remote_user: ansibleuser
  
  tasks:
    - name: Install GlusterFS server
      apt:
        name: glusterfs-server
        state: present
        update_cache: yes

    - name: Start and enable GlusterFS service
      systemd:
        name: glusterd
        enabled: yes
        state: started

- name: Configure GlusterFS Storage
  hosts: ubuntu
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: List all NVMe devices
      command: ls /dev/nvme*n1
      register: nvme_devices
      changed_when: false
      failed_when: false

    - name: Create physical volumes on all NVMe devices
      lvg:
        vg: "glustervg"
        pvs: "{{ nvme_devices.stdout_lines }}"
      when: nvme_devices.stdout_lines | length > 0

    - name: Create a volume group 'glustervg' on NVMe devices
      lvg:
        vg: "glustervg"
        pvs: "{{ nvme_devices.stdout_lines }}"
        state: present
      when: nvme_devices.stdout_lines | length > 0

    - name: Create a logical volume that uses 100% of the volume group space
      lvol:
        vg: "glustervg"
        lv: "glusterlv"
        size: 100%VG
      when: nvme_devices.stdout_lines | length > 0

    - name: Format the logical volume with XFS
      filesystem:
        fstype: xfs
        dev: "/dev/glustervg/glusterlv"
      when: nvme_devices.stdout_lines | length > 0

    - name: Mount the logical volume
      mount:
        path: "/glusterfs"
        src: "/dev/glustervg/glusterlv"
        fstype: xfs
        state: mounted
        opts: defaults
      when: nvme_devices.stdout_lines | length > 0

- name: Setup GlusterFS Trusted Pool
  hosts: ubuntu
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: Probe other nodes with NVMe drives into the cluster
      command: gluster peer probe {{ item }}
      loop: "{{ groups['all'] }}"
      when: hostvars[item]['nvme_devices']['stdout_lines'] | length > 0
      ignore_errors: yes

- name: Create GlusterFS Volume
  hosts: r730:x3650
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: Create a replicated GlusterFS volume
      command: >
        gluster volume create gv0 replica {{ groups['all'] | length }}
        {% for host in groups['all'] %}
        {% if hostvars[host]['nvme_devices']['stdout_lines'] | length > 0 %}
        {{ host }}:/glusterfs
        {% endif %}
        {% endfor %}
        force
      run_once: true
      ignore_errors: yes

    - name: Start the GlusterFS volume
      command: gluster volume start gv0
      run_once: true

- name: Mount GlusterFS Volume on All Nodes
  hosts: ubuntu
  become: yes
  remote_user: ansibleuser

  tasks:
    - name: Create a mount point directory
      file:
        path: /mnt/glusterfs
        state: directory

    - name: Mount the GlusterFS volume
      mount:
        path: /mnt/glusterfs
        src: "{{ groups['r730'][0] }}:/gv0"
        fstype: glusterfs
        state: mounted
