---
- name: Setup CephFS on Ubuntu Servers
  hosts: ubuntu
  become: yes
  vars:
    ansible_user: "ubuntu"
    ceph_client_name: "k3suser"
    ceph_admin_key: "AQABl8VlyvEkOhAAI84zOAHfUuZSkGkpGITwuA=="
    monitor_ips: "192.168.68.135,192.168.68.99,192.168.68.127"
    ceph_fsid: "bdb7f01f-af6a-4dab-a236-2eb8075ef90b"
    mount_point: "/mnt/cephfs"
    ceph_secret_file: "/etc/ceph/ceph.client.k3suser.keyring"
    ceph_conf_path: "/etc/ceph/ceph.conf"
    pv_pvc_definition_path: "/home/ubuntu/pv-pvc-definition.yaml"

  tasks:
    - name: Ensure /etc/ceph directory exists
      file:
        path: "/etc/ceph"
        state: directory
        mode: '0755'

    - name: Create Ceph keyring file for k3suser
      copy:
        dest: "{{ ceph_secret_file }}"
        content: |
          [client.{{ ceph_client_name }}]
          key = {{ ceph_admin_key }}
        mode: '0600'

    - name: Generate ceph.conf file
      copy:
        dest: "{{ ceph_conf_path }}"
        content: |
          [global]
          fsid = {{ ceph_fsid }}
          mon_host = {{ monitor_ips | join(',') }}
        mode: '0644'

- name: Setup Kubernetes Resources for CephFS on localhost
  hosts: localhost
  become: no
  vars:
    ceph_admin_key_base64: "{{ ceph_admin_key | b64encode }}"
    pv_pvc_definition_path: "/home/ubuntu/pv-pvc-definition.yaml"
    ceph_client_name: "k3suser"
    monitor_ips: "192.168.68.135,192.168.68.99,192.168.68.127"
  tasks:
    - name: Create Kubernetes secret for Ceph authentication
      shell: kubectl create secret generic ceph-secret --from-literal=key="{{ ceph_admin_key_base64 }}" --namespace=default
      args:
        executable: /bin/bash

    - name: Generate PV and PVC definition for CephFS
      copy:
        dest: "{{ pv_pvc_definition_path }}"
        content: |
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: cephfs-pv
          spec:
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteMany
            cephfs:
              monitors: [{{ monitor_ips | join('","') }}]
              path: "/"
              user: "{{ ceph_client_name }}"
              secretRef:
                name: ceph-secret
              readOnly: false
            persistentVolumeReclaimPolicy: Retain
          ---
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: cephfs-pvc
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 1Gi
            volumeName: cephfs-pv
        mode: '0644'

    - name: Deploy Persistent Volume and Persistent Volume Claim for CephFS
      shell: kubectl apply -f "{{ pv_pvc_definition_path }}"
      args:
        executable: /bin/bash
