# Teardown Script

- name: Tear Down K3S Cluster
  hosts: manager_nodes
  gather_facts: no
  become: true

  vars:
    kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Remove Deployed Resources From The Cluster
      shell: >
        while [[ $(kubectl delete ns cert-manager prometheus grafana loki logging monitoring templating-resources flux-system longhorn-system) ]] ; do sleep 5; done

    - name: Stop Docker Service
      systemd: name=docker enabled=false state=stopped

    - name: Uninstall Unnecessary Packages
      apt: pkg={{ item }} state=absent purge=yes autoremove=yes
      loop: [ "curl", "jq" ]

    - name: Clean Up Temporary Files Created During Installation Process
      find: paths=/tmp patterns="*.lock *.log" age=-1m recurse=yes
      register: temp_files

    - name: Delete Found Temporary Files
      file: path="{{ item.path }}" state=absent
      loop: "{{ temp_files.files }}"

    - name: Reboot Machine
      reboot:
