---
- name: Deploy VMs to Proxmox Nodes
  hosts: proxmox
  gather_facts: no
  vars:
    proxmox_api_user: root@pam
    proxmox_api_password: your_password
    vm_definitions:
      - name: ubuntu-master
        template: ubuntu-template
      - name: ubuntu-worker
        template: ubuntu-template
  tasks:
    - name: Clone VMs from template
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ ansible_host }}"
        node: "{{ inventory_hostname }}"
        name: "{{ item.name }}"
        clone: "{{ item.template }}"
        state: present
      loop: "{{ vm_definitions }}"
