---
- name: Install pve-fake-subscription and modify /etc/hosts
  hosts: proxmox
  become: true
  vars:
    user: root
    password: bulletx2
    deb_url: "https://github.com/Jamesits/pve-fake-subscription/releases/download/v0.0.9/pve-fake-subscription_0.0.9+git-1_all.deb"
  tasks:
    - name: Download pve-fake-subscription package
      get_url:
        url: "{{ deb_url }}"
        dest: /root/pve-fake-subscription_0.0.9+git-1_all.deb
        mode: 0644
      register: download_result

    - name: Install pve-fake-subscription package
      apt:
        deb: /root/pve-fake-subscription_0.0.9+git-1_all.deb
      when: download_result.changed

    - name: Add entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 shop.maurer-it.com"
        state: present
      notify: Restart Network

  handlers:
    - name: Restart Network
      command: systemctl restart network.service

