---
- name: Enable SSH key access and upload to GitHub
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Generate SSH key pair
      command: ssh-keygen -t rsa -b 4096 -C "alwaysbrother10@gmail.com" -f ~/.ssh/id_rsa -q -N ""

    - name: Copy public key to authorized_keys
      authorized_key:
        user: david
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      vars:
        ansible_ssh_common_args: "-o PasswordAuthentication=yes"

    - name: Test SSH key access
      ping:
      vars:
        ansible_ssh_common_args: "-o PasswordAuthentication=no"

    - name: Install git package
      apt:
        name: git
        state: present

    - name: Configure Git global user
      git_config:
        name: user.name
        value: David
        scope: global

    - name: Configure Git global email
      git_config:
        name: user.email
        value: alwaysbrother10@gmail.com
        scope: global

    - name: Upload SSH key to GitHub
      uri:
        url: "https://api.github.com/user/keys"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "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"
        body: '{"title": "Ubuntu Server", "key": "{{ lookup(''file'', ''~/.ssh/id_rsa.pub'') }}" }'
        body_format: json
        return_content: yes
      register: github_response
      when: YOUR_GITHUB_TOKEN is defined

    - name: Debug GitHub response
      debug:
        var: github_response.json
      when: github_response is defined
