- name: Copy SSH key to multiple hosts using ssh-copy-id
  hosts: ubuntu
  gather_facts: no
  vars:
    ssh_public_key_path: "/home/ubuntu-template/.ssh/id_rsa.pub"
    remote_user: ubuntu

  tasks:
    - name: Install sshpass (required for password-based SSH login)
      ansible.builtin.package:
        name: sshpass
        state: present
      delegate_to: localhost

    - name: Copy SSH public key using ssh-copy-id
      ansible.builtin.shell: |
        sshpass -p "{{ ansible_ssh_pass }}" ssh-copy-id -i {{ ssh_public_key_path }} {{ remote_user }}@{{ inventory_hostname }}
      args:
        executable: /bin/bash
      become: false
      delegate_to: localhost
      ignore_errors: true

- name: Grant ubuntu user passwordless sudo
  hosts: ubuntu
  become: yes
  tasks:
    - name: Ensure ubuntu has passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ubuntu
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        state: present
        create: yes
      become: true
