---
- name: Enable Wake-on-LAN
  hosts: all
  become: yes
  gather_facts: yes
  remote_user: ansibleuser
  tasks:
    - name: Install ethtool
      apt:
        name: ethtool
        state: present

    - name: Set Wake-on-LAN
      command: ethtool -s {{ iface }} wol g

    - name: Verify Wake-on-LAN is enabled
      command: ethtool {{ iface }}
      register: wol_status
      changed_when: false

    - name: Show Wake-on-LAN status
      debug:
        var: wol_status.stdout_lines
