---
- name: Enable Wake-on-LAN
  hosts: all
  become: yes
  gather_facts: yes
  remote_user: ansibleuser
  tasks:
    - name: Install ethtool
      apt:
        name: ethtool
        state: present

    - name: Get network interface name
      shell: |
        ip -o -4 route show to default | awk '{print $5}'
      register: interface_name

    - name: Set Wake-on-LAN
      command: ethtool -s {{ interface_name.stdout_lines[0] }} wol g
