services:
  4kbazarr:

    container_name: "4kbazarr"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=4kbazarr"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "d5b39d9fb642"

    image: "linuxserver/bazarr"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v1.4.0-ls234 Build-date:- 2024-01-25T02:35:24+00:00"
      maintainer: "chbmb"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:6767]"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2024-01-25T02:35:24+00:00"
      org.opencontainers.image.description: "[Bazarr](https://www.bazarr.media/) is a companion application\
        \ to Sonarr and Radarr. It can manage and download subtitles based on your requirements. You define\
        \ your preferences by TV show or movie and Bazarr takes care of everything for you."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-bazarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "553e7cbdf721df31709f7ce40db77913a15218ae"
      org.opencontainers.image.revision: "553e7cbdf721df31709f7ce40db77913a15218ae"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-bazarr"
      org.opencontainers.image.title: "Bazarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-bazarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v1.4.0-ls234"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:1e"

    network_mode: "bridge"

    ports:
      - "6768:6767/tcp"

    volumes:
      - "/mnt/user/appdata/4kbazarr:/config"
      - "/mnt/user/data/media/4k/movies:/movies"
      - "/mnt/user/data/media/4k/tv:/tv"

    working_dir: "/"

version: "3.6"
