services:
  DiskSpeed:

    command:
      - "catalina.sh"
      - "run"

    container_name: "DiskSpeed"

    environment:
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=DiskSpeed"
      - "PATH=/usr/local/tomcat/bin:/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "JAVA_HOME=/opt/java/openjdk"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US:en"
      - "LC_ALL=en_US.UTF-8"
      - "JAVA_VERSION=jdk-11.0.20+8"
      - "CATALINA_HOME=/usr/local/tomcat"
      - "TOMCAT_NATIVE_LIBDIR=/usr/local/tomcat/native-jni-lib"
      - "LD_LIBRARY_PATH=/usr/local/tomcat/native-jni-lib"
      - "GPG_KEYS=48F8E69F6390C9F25CFEDCD268248959359E722B A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 DCFD35E0BF8CA7344752DE8B6FB21E8933C60243"
      - "TOMCAT_MAJOR=9"
      - "TOMCAT_VERSION=9.0.78"
      - "TOMCAT_SHA512=c9f2e60489d07f25b53f715918f4b082c5bb69dbc497e0a9d3d5e3a0d351ff2e0ec8dfc5657de840ee5b3dea6174b27630033b38e36fa4c06b08664e70dec8df"
      - "LUCEE_JAVA_OPTS=-Xms64m -Xmx512m"

    hostname: "48393c41d576"

    image: "jbartlett777/diskspeed"

    ipc: "private"

    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/jbartlett777/DiskSpeed/master/DiskSpeed.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8888]/"
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.version: "22.04"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    ports:
      - "18888:8888/tcp"

    privileged: true

    security_opt:
      - "label=disable"

    volumes:
      - "/mnt/cache/appdata/DiskSpeed:/tmp/DiskSpeed"
      - "/var/local/emhttp:/var/local/emhttp:ro"

    working_dir: "/usr/local/tomcat"

version: "3.6"
