services:
  Dozzle:

    container_name: "Dozzle"

    entrypoint:
      - "/dozzle"

    environment:
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=Dozzle"
      - "DOZZLE_BASE=/"
      - "DOZZLE_LEVEL=info"
      - "DOZZLE_TAILSIZE=300"
      - "DOZZLE_USERNAME="
      - "DOZZLE_PASSWORD="
      - "DOZZLE_NO_ANALYTICS=true"
      - "TZ=America/Los_Angeles"
      - "DOZZLE_KEY=9Q9SJ69MZhZ0WrjbF"
      - "PATH=/bin"

    hostname: "f623e0013e71"

    image: "amir20/dozzle"

    ipc: "private"

    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/dozzle.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8080]/"
      org.opencontainers.image.created: "2024-01-24T18:30:13.931Z"
      org.opencontainers.image.description: "Realtime log viewer for docker containers."
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.revision: "025ce2813460b244bea60866c942cc28a83e8756"
      org.opencontainers.image.source: "https://github.com/amir20/dozzle"
      org.opencontainers.image.title: "dozzle"
      org.opencontainers.image.url: "https://github.com/amir20/dozzle"
      org.opencontainers.image.version: "v6.1.1"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:0b"

    network_mode: "bridge"

    ports:
      - "5050:8080/tcp"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    working_dir: "/"

version: "3.6"
