services:
  frigate:
    container_name: "frigate"
    entrypoint:
      - "/init"
    environment:
      - "NVIDIA_VISIBLE_DEVICES=GPU-3f900cb9-08b7-5725-a2c5-d18fc5e9273b"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,utility,video"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=frigate"
      - "FRIGATE_RTSP_PASSWORD=frigate"
      - "PATH=/usr/lib/btbn-ffmpeg/bin:/usr/local/go2rtc/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "S6_LOGGING_SCRIPT=T 1 n0 s10000000 T"
    hostname: "12a229b3b36b"
    image: "ghcr.io/blakeblackshear/frigate:stable-tensorrt"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:5000]"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    network_mode: "bridge"
    ports:
      - "1984:1984/tcp"
      - "5001:5000/tcp"
      - "8554:8554/tcp"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/mnt/user/NVR/frigate:/media/frigate"
      - "/mnt/user/appdata/frigate:/config"
    working_dir: "/opt/frigate"

version: "3.6"
