services:
  immich:

    container_name: "immich"

    entrypoint:
      - "/init"

    environment:
      - "DISABLE_TYPESENSE=false"
      - "MACHINE_LEARNING_WORKERS=1"
      - "PGID=100"
      - "DISABLE_MACHINE_LEARNING=false"
      - "HOST_HOSTNAME=Tower"
      - "DB_DATABASE_NAME=immich"
      - "REDIS_PASSWORD=immich"
      - "TZ=America/Los_Angeles"
      - "DB_PASSWORD=immich"
      - "DB_PORT=5432"
      - "REDIS_PORT=6379"
      - "MACHINE_LEARNING_WORKER_TIMEOUT=120"
      - "PUID=99"
      - "DB_HOSTNAME=192.168.68.133"
      - "HOST_CONTAINERNAME=immich"
      - "DB_USERNAME=immich"
      - "REDIS_HOSTNAME=192.168.68.133"
      - "UMASK=022"
      - "HOST_OS=Unraid"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "IMMICH_MACHINE_LEARNING_URL=http://127.0.0.1:3003"
      - "IMMICH_MEDIA_LOCATION=/photos"
      - "MACHINE_LEARNING_CACHE_FOLDER=/config/machine-learning"
      - "TRANSFORMERS_CACHE=/config/machine-learning"
      - "SERVER_PORT=8080"
      - "IMMICH_WEB_ROOT=/app/immich/server/www"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "NODE_ENV=production"

    hostname: "2895f53fedfb"

    image: "ghcr.io/imagegenius/immich"

    ipc: "private"

    labels:
      build_version: "ImageGenius Version:- v1.93.3-ig243 Build-date:- 2024-01-25T02:48:52+11:00"
      maintainer: "hydazz, martabal"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8080]"
      org.opencontainers.image.authors: "imagegenius.io"
      org.opencontainers.image.created: "2024-01-25T02:48:52+11:00"
      org.opencontainers.image.description: "Immich is a high performance self-hosted photo and video\
        \ backup solution."
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "3d6f6121a2e7c21b164e4502dcadfb85ddae6086"
      org.opencontainers.image.revision: "3d6f6121a2e7c21b164e4502dcadfb85ddae6086"
      org.opencontainers.image.source: "https://github.com/imagegenius/docker-immich"
      org.opencontainers.image.title: "Immich"
      org.opencontainers.image.url: "https://github.com/imagegenius/docker-immich/packages"
      org.opencontainers.image.vendor: "imagegenius.io"
      org.opencontainers.image.version: "v1.93.3-ig243"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    ports:
      - "7005:8080/tcp"

    volumes:
      - "/mnt/user/appdata/immich/model:/config/machine-learning"
      - "/mnt/user/appdata/immich:/config"
      - "/mnt/user/cloud/immich:/photos"
      - "1f8315a2e947865edfb8b60052fe2f18456b4aac35d1da96f4778c1027401b53::/import:ro"
      - "d622fb6fd3819d02c31a7dba9315e9a2c7ce1f96417ee7acdd637204baa1f4df:/uploads"
      - "e33c7af37947f52b17b31535abacfabc232617df6190660770dcd8b4ce379583:/import"

    working_dir: "/"

version: "3.6"

volumes:
  1f8315a2e947865edfb8b60052fe2f18456b4aac35d1da96f4778c1027401b53:
    external: true
  d622fb6fd3819d02c31a7dba9315e9a2c7ce1f96417ee7acdd637204baa1f4df:
    external: true
  e33c7af37947f52b17b31535abacfabc232617df6190660770dcd8b4ce379583:
    external: true
