services:
  jellyseerr:
    command:
      - "yarn"
      - "start"
    container_name: "jellyseerr"
    entrypoint:
      - "/sbin/tini"
      - "--"
    environment:
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=jellyseerr"
      - "LOG_LEVEL=info"
      - "PUID=99"
      - "PGID=100"
      - "UMASK=022"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=16.17.1"
      - "YARN_VERSION=1.22.19"
    hostname: "7daa8c63e757"
    image: "fallenbagel/jellyseerr:latest"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/Fallenbagel/jellyseerr/main/public/android-chrome-512x512.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:5055]/"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    mac_address: "02:42:ac:11:00:04"
    network_mode: "bridge"
    ports:
      - "5055:5055/tcp"
    restart: "unless-stopped"
    volumes:
      - "/mnt/user/appdata/jellyseerr:/app/config"
    working_dir: "/app"

version: "3.6"
