services:
  jellyplex-watched:

    command:
      - "python"
      - "-u"
      - "main.py"

    container_name: "jellyplex-watched"

    entrypoint:
      - "/sbin/tini"
      - "--"

    environment:

      - "SYNC_FROM_JELLYFIN_TO_JELLYFIN =True"

      - "PLEX_PASSWORD="

      - "JELLYFIN_TOKEN=e7075c6f6ef24ffabff43f6fdfc3ad6e"

      - "SLEEP_DURATION=3600"

      - "WHITELIST_USERS="

      - "LOGFILE=/tmp/log.log"

      - "HOST_CONTAINERNAME=jellyplex-watched"

      - "PLEX_USERNAME="

      - "JELLYFIN_BASEURL=http://192.168.68.133:8096"

      - "TZ=America/Los_Angeles"

      - "WHITELIST_LIBRARY="

      - "PLEX_SERVERNAME="

      - "USER_MAPPING={\"blackops010\" : \"admin\", \"reaghan\" : \"reaghan1\", \"luken0306\" : \"luken83\"\
        }"

      - "SYNC_FROM_PLEX_TO_JELLYFIN =True"

      - "DEBUG=True"

      - "PLEX_TOKEN=cFVjEf3ZE8DY5f68W-kf"

      - "HOST_OS=Unraid"

      - "LIBRARY_MAPPING={ \"Tv Shows\" : \"Shows\"}"

      - "BLACKLIST_USERS="

      - "PLEX_BASEURL=http://192.168.68.133:32400"

      - "HOST_HOSTNAME=Tower"

      - "DEBUG_LEVEL=INFO"

      - "BLACKLIST_LIBRARY="

      - "BLACKLIST_LIBRARY_TYPE="

      - "WHITELIST_LIBRARY_TYPE="

      - "SYNC_FROM_JELLYFIN_TO_PLEX =True"

      - "SYNC_FROM_PLEX_TO_PLEX =True"

      - "SSL_BYPASS=True"

      - "DRYRUN=True"

      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

      - "LANG=C.UTF-8"

      - "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D"

      - "PYTHON_VERSION=3.11.7"

      - "PYTHON_PIP_VERSION=23.2.1"

      - "PYTHON_SETUPTOOLS_VERSION=65.5.1"

      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/049c52c665e8c5fd1751f942316e0a5c777d304f/public/get-pip.py"

      - "PYTHON_GET_PIP_SHA256=7cfd4bdc4d475ea971f1c0710a5953bcc704d171f83c797b9529d9974502fcc6"

      - "RUN_ONLY_ONCE=False"

      - "MARKFILE=mark.log"

      - "SYNC_FROM_PLEX_TO_JELLYFIN=True"

      - "SYNC_FROM_JELLYFIN_TO_PLEX=True"

      - "SYNC_FROM_PLEX_TO_PLEX=True"

      - "SYNC_FROM_JELLYFIN_TO_JELLYFIN=True"

    hostname: "5595a28b023b"

    image: "luigi311/jellyplex-watched:latest"

    ipc: "private"

    labels:
      net.unraid.docker.managed: "dockerman"
      org.opencontainers.image.created: "2024-01-26T00:54:57.867Z"
      org.opencontainers.image.description: "Sync watched between jellyfin and plex locally"
      org.opencontainers.image.licenses: "GPL-3.0"
      org.opencontainers.image.revision: "86b30e18873e1a2137e86465c521f416f9991198"
      org.opencontainers.image.source: "https://github.com/luigi311/JellyPlex-Watched"
      org.opencontainers.image.title: "JellyPlex-Watched"
      org.opencontainers.image.url: "https://github.com/luigi311/JellyPlex-Watched"
      org.opencontainers.image.version: "main-alpine"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:07"

    network_mode: "bridge"

    user: "jellyplex_user"

    working_dir: "/app"

version: "3.6"
