services:
  jellyfin:

    container_name: "jellyfin"

    entrypoint:
      - "/init"

    environment:
      - "PGID=100"
      - "UMASK=022"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=jellyfin"
      - "JELLYFIN_PublishedServerUrl=192.168.68.122"
      - "PUID=99"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"

    hostname: "86e655437f19"

    image: "lscr.io/linuxserver/jellyfin"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 10.8.13-1-ls242 Build-date:- 2024-01-23T12:47:21+00:00"
      maintainer: "thelamer"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8096]"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2024-01-23T12:47:21+00:00"
      org.opencontainers.image.description: "[Jellyfin](https://github.com/jellyfin/jellyfin) is a Free\
        \ Software Media System that puts you in control of managing and streaming your media. It is an\
        \ alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user\
        \ devices via multiple apps. Jellyfin is descended from Emby's 3.5.2 release and ported to the\
        \ .NET Core framework to enable full cross-platform support. There are no strings attached, no\
        \ premium licenses or features, and no hidden agendas: just a team who want to build something\
        \ better and work together to achieve it."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-jellyfin"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "f70f1831a8bb3a4e6085e0b11794b56dbf737154"
      org.opencontainers.image.revision: "f70f1831a8bb3a4e6085e0b11794b56dbf737154"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-jellyfin"
      org.opencontainers.image.title: "Jellyfin"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-jellyfin/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "10.8.13-1-ls242"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:10"

    network_mode: "bridge"

    ports:
      - "1900:1900/udp"
      - "7359:7359/udp"
      - "8096:8096/tcp"
      - "8920:8920/tcp"

    privileged: true

    security_opt:
      - "label=disable"

    volumes:
      - "/mnt/user/appdata/jellyfin:/config"
      - "/mnt/user/data/media/4k/movies:/data/movies"
      - "/mnt/user/data/media/4k/tv:/data/tvshows"
      - "/mnt/user/data/media/music:/data/music"
      - "/mnt/user/data/plex_streaming:/plex-debrid"
      - "/mnt/user/data/plex_toggle:/debrid"

    working_dir: "/"

version: "3.6"
