services:
  mariadb-nextcloud:

    container_name: "mariadb-nextcloud"

    entrypoint:
      - "/init"

    environment:
      - "HOST_HOSTNAME=Tower"
      - "MYSQL_PASSWORD=nextcloud"
      - "HOST_CONTAINERNAME=mariadb-nextcloud"
      - "MYSQL_ROOT_PASSWORD=nextcloud"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql"
      - "PUID=99"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "PGID=100"
      - "UMASK=022"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "MYSQL_DIR=/config"
      - "DATADIR=/config/databases"

    hostname: "8fb05816d8c3"

    image: "lscr.io/linuxserver/mariadb"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 10.11.5-r0-ls124 Build-date:- 2024-01-02T07:44:02+00:00"
      maintainer: "thelamer,nemchik"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mariadb-logo.png"
      net.unraid.docker.managed: "dockerman"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2024-01-02T07:44:02+00:00"
      org.opencontainers.image.description: "[Mariadb](https://mariadb.org/) is one of the most popular\
        \ database servers. Made by the original developers of MySQL."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-mariadb"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "9d70945e657cdbc0ccf01be8c27d1f99802a7fe9"
      org.opencontainers.image.revision: "9d70945e657cdbc0ccf01be8c27d1f99802a7fe9"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-mariadb"
      org.opencontainers.image.title: "Mariadb"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-mariadb/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "10.11.5-r0-ls124"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:26"

    network_mode: "bridge"

    ports:
      - "3307:3306/tcp"

    volumes:
      - "/mnt/user/appdata/mariadb-nextcloud:/config"

    working_dir: "/"

version: "3.6"
