services:
  nextcloud:

    container_name: "nextcloud"

    entrypoint:
      - "/init"

    environment:
      - "PUID=99"
      - "PGID=100"
      - "UMASK=022"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=nextcloud"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "LD_PRELOAD=/usr/lib/preloadable_libiconv.so"

    hostname: "d9afbdfb6255"

    image: "lscr.io/linuxserver/nextcloud:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 28.0.1-ls296 Build-date:- 2024-01-09T11:55:59+00:00"
      maintainer: "aptalca"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-logo.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://[IP]:[PORT:443]"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2024-01-09T11:55:59+00:00"
      org.opencontainers.image.description: "[Nextcloud](https://nextcloud.com/) gives you access to all\
        \ your files wherever you are.    Where are your photos and documents? With Nextcloud you pick\
        \ a server of your choice, at home, in a data center or at a provider. And that is where your\
        \ files will be. Nextcloud runs on that server, protecting your data and giving you access from\
        \ your desktop or mobile devices. Through Nextcloud you also access, sync and share your existing\
        \ data on that FTP drive at the office, a Dropbox or a NAS you have at home.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-nextcloud"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "2d4551b309770bf0165980b99ecd18712df8479d"
      org.opencontainers.image.revision: "2d4551b309770bf0165980b99ecd18712df8479d"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-nextcloud"
      org.opencontainers.image.title: "Nextcloud"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-nextcloud/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "28.0.1-ls296"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:27"

    network_mode: "bridge"

    ports:
      - "4435:443/tcp"

    volumes:
      - "/mnt/user/appdata/nextcloud:/config"
      - "/mnt/user/cloud/nextcloud:/data"

    working_dir: "/"

version: "3.6"
