services:
  overseerr:

    container_name: "overseerr"

    entrypoint:
      - "/init"

    environment:
      - "PUID=99"
      - "PGID=100"
      - "UMASK=022"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=overseerr"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/config"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "421702e959ea"

    image: "lscr.io/linuxserver/overseerr"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v1.33.2-ls90 Build-date:- 2024-01-10T18:36:43+00:00"
      maintainer: "nemchik"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/overseerr-logo.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:5055]"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2024-01-10T18:36:43+00:00"
      org.opencontainers.image.description: "[Overseerr](https://overseerr.dev/) is a request management\
        \ and media discovery tool built to work with your existing Plex ecosystem.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-overseerr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "379018a0d680a08786593851ef26432cf03fb57a"
      org.opencontainers.image.revision: "379018a0d680a08786593851ef26432cf03fb57a"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-overseerr"
      org.opencontainers.image.title: "Overseerr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-overseerr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v1.33.2-ls90"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    ports:
      - "5056:5055/tcp"

    volumes:
      - "/mnt/user/appdata/overseerr:/config"

    working_dir: "/"

version: "3.6"
