services:
  Plex-debrid:
    command:
      - "python"
      - "./main.py"
      - "--config-dir"
      - "config"
      - "-e"
      - "TERM=xterm"
    container_name: "Plex-debrid"
    environment:
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=Plex-debrid"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
      - "PYTHON_VERSION=3.12.0"
      - "PYTHON_PIP_VERSION=23.2.1"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/c6add47b0abf67511cdfb4734771cbab403af062/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=22b849a10f86f5ddf7ce148ca2a31214504ee6c83ef626840fde6e5dcd809d11"
      - "TERM=xterm"
    hostname: "Tower"
    image: "docker.io/itstoggle/plex_debrid:latest"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://avatars.githubusercontent.com/u/71379623?s=48&v=4"
      net.unraid.docker.managed: "dockerman"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    network_mode: "host"
    stdin_open: true
    tty: true
    volumes:
      - "/mnt/user/appdata/plex_toggle:/config"

version: "3.6"
