services:
  plex-utills:

    command:
      - "/app/start.sh"

    container_name: "plex-utills"

    environment:
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=plex-utills"
      - "PUID=99"
      - "PGID=100"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
      - "PYTHON_VERSION=3.9.16"
      - "PYTHON_PIP_VERSION=22.0.4"
      - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/66030fa03382b4914d4c4d0896961a0bdeeeb274/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=1e501cf004eac1b7eb1f97266d28f995ae835d30250bec7f8850562703067dc6"

    hostname: "04aeadb5e749"

    image: "jkirkcaldy/plex-utills"

    ipc: "private"

    labels:
      discord: "= https://discord.gg/z3FYhHwHMw"
      maintainer: "JKirkcaldy"
      net.unraid.docker.icon: "https://github.com/jkirkcaldy/plex-utills/blob/7cf707f3aee6aa865a811b88d9ced865626bf7bd/app/img/plex-utills_square.png?raw=1"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:80]"
      org.opencontainers.image.created: "2023-02-02T11:52:30.944Z"
      org.opencontainers.image.description: "Manage your Plex library automatically"
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.revision: "e945c0cb113b8ec3bb0b0f15c544f600e6e16d3f"
      org.opencontainers.image.source: "https://github.com/jkirkcaldy/plex-utills"
      org.opencontainers.image.title: "plex-utills"
      org.opencontainers.image.url: "https://github.com/jkirkcaldy/plex-utills"
      org.opencontainers.image.version: "master"
      support: "= https://github.com/jkirkcaldy/plex-utills"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:07"

    network_mode: "bridge"

    ports:
      - "805:80/tcp"

    volumes:
      - "/mnt/cache/appdata/plex-utills/logs:/logs"
      - "/mnt/user/appdata/plex-utills:/config"
      - "/mnt/user/data/media/4k:/films:ro"

    working_dir: "/app"

version: "3.6"
