services:
  rdt-client:

    container_name: "rdt-client"

    entrypoint:
      - "/init"

    environment:
      - "UMASK=022"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=rdt-client"
      - "PUID=99"
      - "PGID=100"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "TARGETPLATFORM=linux/amd64"
      - "BUILDPLATFORM=linux/amd64"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "RDTCLIENT_BRANCH=main"

    hostname: "5fe87a17cf63"

    image: "rogerfar/rdtclient:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io extended version:-  Build-date:- "
      maintainer: "ravensorb"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/fizzyfrys/unraid-templates/main/icons/premrealldebrid.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:6500]"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2024-01-22T00:12:18.723Z"
      org.opencontainers.image.description: "Real-Debrid Client Proxy"
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-baseimage-alpine"
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.ref.name: "b67ba8c8ff041aa4fea6d12c18ea839250b6b58f"
      org.opencontainers.image.revision: "e85366f874876b3c4337bfd482f2a4b339c4e4d9"
      org.opencontainers.image.source: "https://github.com/rogerfar/rdt-client"
      org.opencontainers.image.title: "rdt-client"
      org.opencontainers.image.url: "https://github.com/rogerfar/rdt-client"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "2.0.59"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    ports:
      - "6500:6500/tcp"

    volumes:
      - "/mnt/user/appdata/rdt-client/db:/data/db"
      - "/mnt/user/data:/data"

    working_dir: "/app"

version: "3.6"
