services:
  redis-immich:

    command:
      - "/opt/bitnami/scripts/redis/run.sh"

    container_name: "redis-immich"

    entrypoint:
      - "/opt/bitnami/scripts/redis/entrypoint.sh"

    environment:
      - "HOST_CONTAINERNAME=redis-immich"
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_PASSWORD=immich"
      - "REDIS_EXTRA_FLAGS=--auto-aof-rewrite-percentage 100 --auto-aof-rewrite-min-size 64mb"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "PATH=/opt/bitnami/common/bin:/opt/bitnami/redis/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/"
      - "OS_ARCH=amd64"
      - "OS_FLAVOUR=debian-11"
      - "OS_NAME=linux"
      - "APP_VERSION=7.2.4"
      - "BITNAMI_APP_NAME=redis"

    hostname: "ffc10f5df249"

    image: "bitnami/redis:latest"

    ipc: "private"

    labels:
      com.vmware.cp.artifact.flavor: "sha256:1e1b4657a77f0d47e9220f0c37b9bf7802581b93214fff7d1bd2364c8bf22e8e"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/redis.png"
      net.unraid.docker.managed: "dockerman"
      org.opencontainers.image.base.name: "docker.io/bitnami/minideb:bullseye"
      org.opencontainers.image.created: "2024-01-09T13:35:21Z"
      org.opencontainers.image.description: "Application packaged by VMware, Inc"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.ref.name: "7.2.4-debian-11-r0"
      org.opencontainers.image.title: "redis"
      org.opencontainers.image.vendor: "VMware, Inc."
      org.opencontainers.image.version: "7.2.4"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    ports:
      - "6379:6379/tcp"

    user: "1001"

    volumes:
      - "/mnt/user/appdata/redis-immich:/bitnami/redis"

version: "3.6"
