services:
  SearXNG:

    container_name: "SearXNG"

    entrypoint:
      - "/sbin/tini"
      - "--"
      - "/usr/local/searxng/dockerfiles/docker-entrypoint.sh"

    environment:
      - "INSTANCE_NAME=unraid"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=SearXNG"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "AUTOCOMPLETE="
      - "BASE_URL="
      - "MORTY_KEY="
      - "MORTY_URL="
      - "SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml"
      - "UWSGI_SETTINGS_PATH=/etc/searxng/uwsgi.ini"
      - "UWSGI_WORKERS=%k"
      - "UWSGI_THREADS=4"

    hostname: "7e5003431be0"

    image: "searxng/searxng"

    ipc: "private"

    labels:
      description: "A privacy-respecting, hackable metasearch engine."
      maintainer: "searxng <https://github.com/searxng/searxng>"
      net.unraid.docker.icon: "https://github.com/kilrah/unraid-docker-templates/raw/main/icons/searxng.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8080]/"
      org.label-schema.build-date: "2024-01-25T05:16:15Z"
      org.label-schema.name: "searxng"
      org.label-schema.schema-version: "1.0"
      org.label-schema.url: "https://github.com/searxng/searxng"
      org.label-schema.usage: "https://github.com/searxng/searxng-docker"
      org.label-schema.vcs-ref: "8c73aa772b7d4446f77be82d8f9d9eef1e348deb"
      org.label-schema.vcs-url: "https://github.com/searxng/searxng"
      org.label-schema.version: "2024.1.25+8c73aa772"
      org.opencontainers.image.created: "2024-01-25T05:16:15Z"
      org.opencontainers.image.documentation: "https://github.com/searxng/searxng-docker"
      org.opencontainers.image.revision: "8c73aa772b7d4446f77be82d8f9d9eef1e348deb"
      org.opencontainers.image.source: "https://github.com/searxng/searxng"
      org.opencontainers.image.title: "searxng"
      org.opencontainers.image.url: "https://github.com/searxng/searxng"
      org.opencontainers.image.version: "2024.1.25-8c73aa772"
      version: "2024.1.25+8c73aa772"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    mac_address: "02:42:ac:11:00:03"

    network_mode: "bridge"

    ports:
      - "7006:8080/tcp"

    volumes:
      - "/mnt/user/appdata/searxng:/etc/searxng"

    working_dir: "/usr/local/searxng"

version: "3.6"
