services:
  tautulli:

    command:
      - "python"
      - "Tautulli.py"
      - "--datadir"
      - "/config"

    container_name: "tautulli"

    entrypoint:
      - "./start.sh"

    environment:
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=tautulli"
      - "PUID=1000"
      - "PGID=100"
      - "TZ=UTC"
      - "HOST_OS=Unraid"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
      - "PYTHON_VERSION=3.9.18"
      - "PYTHON_PIP_VERSION=23.0.1"
      - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/4cfa4081d27285bda1220a62a5ebf5b4bd749cdb/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=9cc01665956d22b3bf057ae8287b035827bfd895da235bcea200ab3b811790b6"
      - "TAUTULLI_DOCKER=True"

    hostname: "a7ee5d7be011"

    image: "tautulli/tautulli"

    ipc: "private"

    labels:
      maintainer: "Tautulli"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/Tautulli/Tautulli-Unraid-Template/master/img/logo-circle.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:8181]/"

    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"

    network_mode: "bridge"

    ports:
      - "8181:8181/tcp"

    volumes:
      - "/mnt/cache/appdata/tautulli:/config"
      - "/mnt/user/appdata/Plex-Media-Server:/plex"

    working_dir: "/app"

version: "3.6"
