services:
  TubeArchivist-RedisJSON:
    command:
      - "/entrypoint.sh"
    container_name: "TubeArchivist-RedisJSON"
    environment:
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=TubeArchivist-RedisJSON"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "REDISBLOOM_ARGS="
      - "REDISEARCH_ARGS="
      - "REDISJSON_ARGS="
      - "REDISTIMESERIES_ARGS="
      - "REDIS_ARGS="
    hostname: "63baed0d9a66"
    image: "redis/redis-stack-server"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://i.imgur.com/dtGJa5y.jpeg"
      net.unraid.docker.managed: "dockerman"
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.version: "22.04"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    mac_address: "02:42:ac:11:00:24"
    network_mode: "bridge"
    ports:
      - "6379:6379/tcp"
    volumes:
      - "/mnt/user/appdata/TubeArchivist/redis:/data"
version: "3.6"
