services:
  Wizarr:
    container_name: "Wizarr"
    entrypoint:
      - "/docker-entrypoint.sh"
    environment:
      - "APP_URL=https://wizzar.nicholstech.org/"
      - "DISABLE_INBUILT_AUTH=false"
      - "TZ=America/Los_Angeles"
      - "HOST_OS=Unraid"
      - "HOST_HOSTNAME=Tower"
      - "HOST_CONTAINERNAME=Wizarr"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
      - "PYTHON_VERSION=3.12.0"
      - "PYTHON_PIP_VERSION=23.2.1"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/c6add47b0abf67511cdfb4734771cbab403af062/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=22b849a10f86f5ddf7ce148ca2a31214504ee6c83ef626840fde6e5dcd809d11"
      - "DATABASE_DIR=/data/database"
      - "LATEST_FILE=/latest"
    hostname: "7fe0e2b6d6bc"
    image: "ghcr.io/wizarrrr/wizarr"
    ipc: "private"
    labels:
      net.unraid.docker.icon: "https://github.com/Wizarrrr/wizarr/raw/master/screenshots/wizard.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:5690]/"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
    mac_address: "02:42:ac:11:00:21"
    network_mode: "bridge"
    ports:
      - "5690:5690/tcp"
    restart: "unless-stopped"
    volumes:
      - "/mnt/user/appdata/wizarr:/data/database"
    working_dir: "/wizarr/backend"

version: "3.6"
