#!/bin/bash
cd /mnt/user/data/usenet/completed/4kmovies/
find -type d -name '*_UNPACK_*' -exec rm -rf {} +
find -type d -name '*_FAILED_*' -exec rm -rf {} +
cd /mnt/user/data/usenet/completed/4ktv/
find -type d -name '*_UNPACK_*' -exec rm -rf {} +
find -type d -name '*_FAILED_*' -exec rm -rf {} +
