---
- name: Remove SSH key access and delete from GitHub
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Remove SSH key from authorized_keys
      authorized_key:
        user: david
        state: absent
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      vars:
        ansible_ssh_common_args: "-o PasswordAuthentication=yes"

    - name: Delete SSH key from GitHub
      uri:
        url: "https://api.github.com/user/keys/{{ github_key_id }}"
        method: DELETE
        headers:
          Content-Type: "application/json"
          Authorization: "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"
      when: YOUR_GITHUB_TOKEN is defined

    - name: Debug GitHub response
      debug:
        msg: "SSH key deleted from GitHub."
      when: YOUR_GITHUB_TOKEN is defined
