- name: Set timezone to America/New_York
  hosts: all
  become: yes
  tasks:
    - name: Update timezone
      timezone:
        name: America/New_York

- name: Synchronize system time using NTP
  hosts: all
  become: yes
  tasks:
    - name: Install NTP package
      package:
        name: ntp
        state: present

    - name: Configure NTP servers
      template:
        src: ./ntp.conf.j2
        dest: /etc/ntp.conf
      notify:
        - Restart NTP service

  handlers:
    - name: Restart NTP service
      service:
        name: ntp
        state: restarted
